// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class CouponView
{
    public int 優惠卷編號 { get; set; }

    public string 折扣碼 { get; set; }

    public string 名稱 { get; set; }

    public decimal? 使用金額 { get; set; }

    public decimal? 折扣值 { get; set; }

    public DateTime? 啟用日期 { get; set; }

    public DateTime? 截止日期 { get; set; }

    public string 商品類型 { get; set; }

    public string 使用規則 { get; set; }

    public string 備註 { get; set; }

    public bool 啟用狀態 { get; set; }
}