// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using prjTravelPlatformV3.Models;

namespace prjTravelPlatformV3.Models
{
    public partial class dbTravalPlatformContext
    {

        [DbFunction("CalculateDayDiff", "dbo")]
        public static int? CalculateDayDiff(DateTime? fromDateTime, DateTime? toDateTime)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetOrderID", "dbo")]
        public static string GetOrderID()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetOrderID_F", "dbo")]
        public static string GetOrderID_F()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetOrderID_H", "dbo")]
        public static string GetOrderID_H()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetOrderID_I", "dbo")]
        public static string GetOrderID_I()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetOrderID_V", "dbo")]
        public static string GetOrderID_V()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
