// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class DExchangeView
{
    public int 編號 { get; set; }

    public string 商品名稱 { get; set; }

    public int? 所需點數 { get; set; }

    public decimal? 所需金額 { get; set; }

    public int? 庫存數量 { get; set; }

    public string 商品類型 { get; set; }

    public string 圖片 { get; set; }

    public string 備註 { get; set; }
}