// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class FscheduleView
{
    public int 航班時程編號 { get; set; }

    public string 航班代碼 { get; set; }

    public string 出發地 { get; set; }

    public string 目的地 { get; set; }

    public string 航空公司 { get; set; }

    public string 出發時間 { get; set; }

    public string 抵達時間 { get; set; }

    public string 艙等 { get; set; }

    public decimal? 定價 { get; set; }
}