// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class QuestionView
{
    public int 編號 { get; set; }

    public DateTime? 日期 { get; set; }

    public int? 客戶編號 { get; set; }

    public int? 員工編號 { get; set; }

    public string 主旨 { get; set; }

    public string 處理狀態 { get; set; }

    public string 問題類型 { get; set; }
}