// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class RCarRentOrderInfoView
{
    public string 訂單編號 { get; set; }

    public int? 會員編號 { get; set; }

    public string 會員姓名 { get; set; }

    public string 優惠券名稱 { get; set; }

    public string 付款方式 { get; set; }

    public string 付款狀態 { get; set; }

    public string 訂單狀態 { get; set; }

    public string 訂單成立日期 { get; set; }

    public decimal? 訂單總金額 { get; set; }
}