// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class RCarInfoView
{
    public int 車輛編號 { get; set; }

    public string 車牌號碼 { get; set; }

    public string 車輛型號 { get; set; }

    public string 車輛圖檔 { get; set; }

    public string 車所在地 { get; set; }

    public string 所屬公司 { get; set; }

    public bool? 出租狀態 { get; set; }
}