// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TCcompanyInfo
{
    public int FId { get; set; }

    public string FType { get; set; }

    public string FCompanyName { get; set; }

    public string FLanguage { get; set; }

    public string FCountry { get; set; }

    public string FCity { get; set; }

    public int? FPostalCode { get; set; }

    public string FAddress { get; set; }

    public string FPhoneCountryCode { get; set; }

    public string FPhone { get; set; }

    public string FUrl { get; set; }

    public string FNameOfPersonInCharge { get; set; }

    public string FCertificatePath { get; set; }

    public string FContactName { get; set; }

    public string FContactPosition { get; set; }

    public string FContactEmail { get; set; }

    public string FPassword { get; set; }

    public string FContactPhoneCountryCode { get; set; }

    public string FContactPhone { get; set; }

    public int? FContactTimeZone { get; set; }

    public string FIsChecked { get; set; }

    public string FCheckDate { get; set; }

    public string FIsInCooperation { get; set; }

    public byte[] FLogo { get; set; }

    public virtual ICollection<TFflightSchedule> TFflightSchedules { get; set; } = new List<TFflightSchedule>();

    public virtual ICollection<TIproduct> TIproducts { get; set; } = new List<TIproduct>();

    public virtual ICollection<TIsupplierLogistic> TIsupplierLogistics { get; set; } = new List<TIsupplierLogistic>();

    public virtual ICollection<TRcarInfo> TRcarInfos { get; set; } = new List<TRcarInfo>();

    public virtual ICollection<TVproduct> TVproducts { get; set; } = new List<TVproduct>();
}