// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TCustomer
{
    public int FCustomerId { get; set; }

    public string FName { get; set; }

    public string FPassword { get; set; }

    public string FEmail { get; set; }

    public string FGender { get; set; }

    public string FBirth { get; set; }

    public string FIdentityNumber { get; set; }

    public string FPhone { get; set; }

    public string FAddress { get; set; }

    public int? FLevelId { get; set; }

    public int? FPoint { get; set; }

    public string FRegisterDate { get; set; }

    public string FImagePath { get; set; }

    public bool? FIsCheck { get; set; }

    public virtual TCustomerLevel FLevel { get; set; }

    public virtual ICollection<TCustomerTravelType> TCustomerTravelTypes { get; set; } = new List<TCustomerTravelType>();

    public virtual ICollection<TExchangeRecord> TExchangeRecords { get; set; } = new List<TExchangeRecord>();

    public virtual ICollection<TForder> TForders { get; set; } = new List<TForder>();

    public virtual ICollection<THorder> THorders { get; set; } = new List<THorder>();

    public virtual ICollection<TIorder> TIorders { get; set; } = new List<TIorder>();

    public virtual ICollection<TQuestion> TQuestions { get; set; } = new List<TQuestion>();

    public virtual ICollection<TRcarRentOrder> TRcarRentOrders { get; set; } = new List<TRcarRentOrder>();

    public virtual ICollection<TVorder> TVorders { get; set; } = new List<TVorder>();

    public virtual ICollection<TdestinationOrder> TdestinationOrders { get; set; } = new List<TdestinationOrder>();

    public virtual ICollection<TtravelOrder> TtravelOrders { get; set; } = new List<TtravelOrder>();
}