// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TCustomerTravelType
{
    public int FId { get; set; }

    public int? FCustomerId { get; set; }

    public int? FTravelTypeId { get; set; }

    public virtual TCustomer FCustomer { get; set; }

    public virtual Ttype FTravelType { get; set; }
}