// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TCusCouponQty
{
    public int Fid { get; set; }

    public int FCustomerId { get; set; }

    public int FCouponId { get; set; }

    public DateTime? FStartDate { get; set; }

    public DateTime? FEndDate { get; set; }

    public bool? FUsed { get; set; }

    public virtual TCouponList FCustomer { get; set; }
}