// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TCustomerLevel
{
    public int FLevelId { get; set; }

    public string FLevel { get; set; }

    public virtual ICollection<TCustomer> TCustomers { get; set; } = new List<TCustomer>();
}