// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TdestinationOrder
{
    public int Fid { get; set; }

    public string ForderId { get; set; }

    public int? FmemberId { get; set; }

    public string FdestinationId { get; set; }

    public int? Fqty { get; set; }

    public string ForderDate { get; set; }

    public string FpayMethod { get; set; }

    public string FpayState { get; set; }

    public int Fcoupomid { get; set; }

    public decimal? Fprice { get; set; }

    public string ForderState { get; set; }

    public virtual TCouponList Fcoupom { get; set; }

    public virtual Tdestination Fdestination { get; set; }

    public virtual TCustomer Fmember { get; set; }

    public virtual ICollection<TdestinationRemark> TdestinationRemarks { get; set; } = new List<TdestinationRemark>();
}