// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TdestinationPhoto
{
    public int FphotoId { get; set; }

    public string FdestinationId { get; set; }

    public string FphotoPath { get; set; }

    public virtual Tdestination Fdestination { get; set; }
}