// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TdestinationDetail
{
    public int FdestinationDetailId { get; set; }

    public string FtravelId { get; set; }

    public string FdestinationId { get; set; }

    public virtual Tdestination Fdestination { get; set; }

    public virtual TtravelPlan Ftravel { get; set; }
}