// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TExchangeItem
{
    public int FProductId { get; set; }

    public string FName { get; set; }

    public int? FPointsRequired { get; set; }

    public decimal? FMoneyRequired { get; set; }

    public int? FProductType { get; set; }

    public int? FQuantity { get; set; }

    public string FImagePath { get; set; }

    public string FNote { get; set; }

    public virtual TProductType FProductTypeNavigation { get; set; }

    public virtual ICollection<TExchangeRecord> TExchangeRecords { get; set; } = new List<TExchangeRecord>();
}