// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TExchangeRecord
{
    public int FId { get; set; }

    public int? FProductId { get; set; }

    public int? FMemberId { get; set; }

    public int? FPoints { get; set; }

    public decimal? FMoneyRequire { get; set; }

    public DateTime? FTransDate { get; set; }

    public int? FQuantity { get; set; }

    public virtual TCustomer FMember { get; set; }

    public virtual TExchangeItem FProduct { get; set; }
}