// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TFairportInfo
{
    public int FAirportId { get; set; }

    public string FAirport { get; set; }

    public virtual ICollection<TFflightSchedule> TFflightScheduleFDepartures { get; set; } = new List<TFflightSchedule>();

    public virtual ICollection<TFflightSchedule> TFflightScheduleFDestinations { get; set; } = new List<TFflightSchedule>();
}