// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TFairline
{
    public int FAirlineId { get; set; }

    public string FAirlineName { get; set; }
}