// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TForder
{
    public int FId { get; set; }

    public string FOrderId { get; set; }

    public int? FMemberId { get; set; }

    public string FOrderDate { get; set; }

    public int? FOrderStatusId { get; set; }

    public int? FPaymentStatusId { get; set; }

    public int? FPaymentId { get; set; }

    public int? FCouponId { get; set; }

    public decimal? FTotal { get; set; }

    public virtual TCouponList FCoupon { get; set; }

    public virtual TCustomer FMember { get; set; }

    public virtual TForderStatus FOrderStatus { get; set; }

    public virtual TFpayment FPayment { get; set; }

    public virtual TForderStatus FPaymentStatus { get; set; }

    public virtual ICollection<TForderDetail> TForderDetails { get; set; } = new List<TForderDetail>();
}