// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TForderStatus
{
    public int FOrderStatusId { get; set; }

    public string FOrderStatus { get; set; }

    public virtual ICollection<TForder> TForderFOrderStatuses { get; set; } = new List<TForder>();

    public virtual ICollection<TForder> TForderFPaymentStatuses { get; set; } = new List<TForder>();
}