// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TForderDetail
{
    public int FOrderDetailId { get; set; }

    public string FOrderId { get; set; }

    public int? FScheduleId { get; set; }

    public int? FTicketTypeId { get; set; }

    public decimal? FPrice { get; set; }

    public string FPsgrName { get; set; }

    public string FNationalId { get; set; }

    public string FPassportNum { get; set; }

    public bool? FGender { get; set; }

    public string FBirth { get; set; }

    public string FEmail { get; set; }

    public string FPhone { get; set; }

    public int? FQrcode { get; set; }

    public virtual TForder FOrder { get; set; }

    public virtual TFflightSchedule FSchedule { get; set; }

    public virtual TFticketType FTicketType { get; set; }
}