// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class THcomment
{
    public int FCommentId { get; set; }

    public int? FCommentScore { get; set; }

    public string FCommentContent { get; set; }

    public int? FCustomerId { get; set; }

    public string FHotelOrderId { get; set; }

    public int? FHotelId { get; set; }

    public string FCommentTime { get; set; }

    public virtual THorder FHotelOrder { get; set; }
}