// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class THorder
{
    public string FHotelOrderId { get; set; }

    public int? FCustomerId { get; set; }

    public int? FHotelId { get; set; }

    public int? FRoomTypeId { get; set; }

    public string FCheckInDate { get; set; }

    public string FCheckOutDate { get; set; }

    public int? FGuestCount { get; set; }

    public int? FRoomCount { get; set; }

    public decimal? FOriginalUnitPrice { get; set; }

    public int? FCouponId { get; set; }

    public int? FQuantity { get; set; }

    public decimal? FTotalPrice { get; set; }

    public int? FPaymentId { get; set; }

    public int? FPaymentStatusId { get; set; }

    public string FOrderDate { get; set; }

    public string FPayDate { get; set; }

    public virtual TCouponList FCoupon { get; set; }

    public virtual TCustomer FCustomer { get; set; }

    public virtual THotel FHotel { get; set; }

    public virtual TRpaymentMethod FPayment { get; set; }

    public virtual TRpaymentStatus FPaymentStatus { get; set; }

    public virtual THroomType FRoomType { get; set; }

    public virtual ICollection<THcomment> THcomments { get; set; } = new List<THcomment>();

    public virtual ICollection<THorderDetail> THorderDetails { get; set; } = new List<THorderDetail>();
}