// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class ThotelDetail
{
    public int FhotelDetailId { get; set; }

    public int? FhotelId { get; set; }

    public string FtravelId { get; set; }

    public virtual TtravelPlan Ftravel { get; set; }
}