// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class THroomFacility
{
    public int FRoomTypeFacilityId { get; set; }

    public string FRoomTypeFacilityName { get; set; }

    public virtual ICollection<THroomTypeFacilityRelation> THroomTypeFacilityRelations { get; set; } = new List<THroomTypeFacilityRelation>();
}