// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class THroom
{
    public int FRoomId { get; set; }

    public string FRoomNumber { get; set; }

    public int FRoomTypeId { get; set; }

    public int FHotelId { get; set; }

    public bool? FRoomStatus { get; set; }

    public virtual THotel FHotel { get; set; }

    public virtual THroomType FRoomType { get; set; }

    public virtual ICollection<THorderDetail> THorderDetails { get; set; } = new List<THorderDetail>();
}