// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TIlogistic
{
    public int FLogisticsId { get; set; }

    public string FLogisticsName { get; set; }

    public decimal? FShipFee { get; set; }

    public virtual ICollection<TIorder> TIorders { get; set; } = new List<TIorder>();

    public virtual ICollection<TIsupplierLogistic> TIsupplierLogistics { get; set; } = new List<TIsupplierLogistic>();
}