// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TIorderDetail
{
    public int FId { get; set; }

    public string FOrderId { get; set; }

    public int? FSpecId { get; set; }

    public int? FQty { get; set; }

    public decimal? FSubtotal { get; set; }

    public virtual TIorder FOrder { get; set; }

    public virtual TIproductSpec FSpec { get; set; }
}