// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TIorderDetailView
{
    public int 編號 { get; set; }

    public string 訂單編號 { get; set; }

    public string 產品名稱 { get; set; }

    public string 規格名稱 { get; set; }

    public int? 購買數量 { get; set; }

    public decimal? 小計 { get; set; }
}