// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TIorder
{
    public int FId { get; set; }

    public string FOrderId { get; set; }

    public int? FMemberId { get; set; }

    public string FOrderDate { get; set; }

    public int? FCoupponId { get; set; }

    public int? FStatusId { get; set; }

    public int? FPayId { get; set; }

    public string FNotes { get; set; }

    public int? FLogisticsId { get; set; }

    public string FShipName { get; set; }

    public string FShipPhone { get; set; }

    public string FShipAddress { get; set; }

    public bool? FReviewed { get; set; }

    public string FLastModified { get; set; }

    public virtual TCouponList FCouppon { get; set; }

    public virtual TIlogistic FLogistics { get; set; }

    public virtual TCustomer FMember { get; set; }

    public virtual TIpayMethod FPay { get; set; }

    public virtual TIorderStatus FStatus { get; set; }

    public virtual ICollection<TIorderDetail> TIorderDetails { get; set; } = new List<TIorderDetail>();
}