// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TIproductSpec
{
    public int FSpecId { get; set; }

    public int? FProductId { get; set; }

    public string FSpecName { get; set; }

    public string FImagePath { get; set; }

    public decimal? FCost { get; set; }

    public decimal? FPrice { get; set; }

    public int? FBuyLimited { get; set; }

    public int? FStockTime { get; set; }

    public string FLastModified { get; set; }

    public virtual TIproduct FProduct { get; set; }

    public virtual ICollection<TIorderDetail> TIorderDetails { get; set; } = new List<TIorderDetail>();

    public virtual ICollection<TIshoppingCart> TIshoppingCarts { get; set; } = new List<TIshoppingCart>();
}