// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TIshoppingCart
{
    public int FShoppingCartId { get; set; }

    public int? FProductId { get; set; }

    public int? FSpecId { get; set; }

    public int? FQty { get; set; }

    public virtual TIproduct FProduct { get; set; }

    public virtual TIproductSpec FSpec { get; set; }
}