// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TplanRemark
{
    public int Fid { get; set; }

    public string FremarkId { get; set; }

    public string ForderId { get; set; }

    public string Fremark { get; set; }

    public virtual TtravelOrder Forder { get; set; }
}