// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TProductType
{
    public int FId { get; set; }

    public string FTypeName { get; set; }

    public string FTypeLetter { get; set; }

    public virtual ICollection<TCouponList> TCouponLists { get; set; } = new List<TCouponList>();

    public virtual ICollection<TExchangeItem> TExchangeItems { get; set; } = new List<TExchangeItem>();

    public virtual ICollection<TQuestion> TQuestions { get; set; } = new List<TQuestion>();
}