// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TQuestion
{
    public int FId { get; set; }

    public DateTime? FDate { get; set; }

    public int? FMemberId { get; set; }

    public int? FEmployeeId { get; set; }

    public string FSubject { get; set; }

    public string FStatus { get; set; }

    public int? FParentId { get; set; }

    public string FType { get; set; }

    public int? FProductType { get; set; }

    public virtual TCustomer FMember { get; set; }

    public virtual TProductType FProductTypeNavigation { get; set; }
}