// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TRcarModel
{
    public int FModelId { get; set; }

    public string FModelName { get; set; }

    public int? FNumOfLuggage { get; set; }

    public int? FNumOfPsgr { get; set; }

    public decimal? FRentalFee { get; set; }

    public string FImagePath { get; set; }

    public bool? FModelInUse { get; set; }

    public virtual ICollection<TRcarInfo> TRcarInfos { get; set; } = new List<TRcarInfo>();
}