// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TRdriverInfo
{
    public int FDriverId { get; set; }

    public string FId { get; set; }

    public string FName { get; set; }

    public string FPhone { get; set; }

    public string FLicenseImagePath { get; set; }

    public virtual ICollection<TRcarRentOrderDetail> TRcarRentOrderDetails { get; set; } = new List<TRcarRentOrderDetail>();
}