// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TRorderStatus
{
    public int FOrderStatusId { get; set; }

    public string FOrderStatus { get; set; }

    public virtual ICollection<TRcarRentOrder> TRcarRentOrders { get; set; } = new List<TRcarRentOrder>();
}