// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TRpaymentMethod
{
    public int FPaymentId { get; set; }

    public string FPayment { get; set; }

    public virtual ICollection<THorder> THorders { get; set; } = new List<THorder>();

    public virtual ICollection<TRcarRentOrder> TRcarRentOrders { get; set; } = new List<TRcarRentOrder>();
}