// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TtravelPlan
{
    public int Fid { get; set; }

    public string FtravelId { get; set; }

    public string FtravelName { get; set; }

    public int? FtravelTypeId { get; set; }

    public string FtravelContent { get; set; }

    public int? Fday { get; set; }

    public string Ftransport { get; set; }

    public int? FareaId { get; set; }

    public int? Fprice { get; set; }

    public int? Fstock { get; set; }

    public bool? Fstate { get; set; }

    public virtual TtravelArea Farea { get; set; }

    public virtual Ttype FtravelType { get; set; }

    public virtual ICollection<TdestinationDetail> TdestinationDetails { get; set; } = new List<TdestinationDetail>();

    public virtual ICollection<ThotelDetail> ThotelDetails { get; set; } = new List<ThotelDetail>();

    public virtual ICollection<TtravelOrder> TtravelOrders { get; set; } = new List<TtravelOrder>();
}