// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TtravelArea
{
    public int FareaId { get; set; }

    public string FareaName { get; set; }

    public virtual ICollection<Tdestination> Tdestinations { get; set; } = new List<Tdestination>();

    public virtual ICollection<TtravelPlan> TtravelPlans { get; set; } = new List<TtravelPlan>();
}