// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class Ttype
{
    public int FtypeId { get; set; }

    public string Ftype { get; set; }

    public virtual ICollection<TCustomerTravelType> TCustomerTravelTypes { get; set; } = new List<TCustomerTravelType>();

    public virtual ICollection<Tdestination> Tdestinations { get; set; } = new List<Tdestination>();

    public virtual ICollection<TtravelPlan> TtravelPlans { get; set; } = new List<TtravelPlan>();
}