// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TVorder
{
    public int FId { get; set; }

    public string FOrderId { get; set; }

    public int FProductId { get; set; }

    public int FCustomerId { get; set; }

    public decimal? FPrice { get; set; }

    public int FQuantity { get; set; }

    public string FDepartureDate { get; set; }

    public string FForPickupOrDeliveryAddress { get; set; }

    public bool? FInterviewReminder { get; set; }

    public int? FEvaluate { get; set; }

    public string FMemo { get; set; }

    public int? FStatusId { get; set; }

    public int? FCouponId { get; set; }

    public virtual TCouponList FCoupon { get; set; }

    public virtual TCustomer FCustomer { get; set; }

    public virtual TVproduct FProduct { get; set; }

    public virtual TVorderStatus FStatus { get; set; }

    public virtual ICollection<TVtravelerInfo> TVtravelerInfos { get; set; } = new List<TVtravelerInfo>();
}