// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TVorderStatus
{
    public int FId { get; set; }

    public string FVorderStatus { get; set; }

    public virtual ICollection<TVorder> TVorders { get; set; } = new List<TVorder>();
}