// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TVprocessingTime
{
    public int FId { get; set; }

    public int FProcessingTime { get; set; }

    public virtual ICollection<TVproduct> TVproducts { get; set; } = new List<TVproduct>();
}