// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class TVtravelerInfo
{
    public int FId { get; set; }

    public int FOrderId { get; set; }

    public string FName { get; set; }

    public bool? FGender { get; set; }

    public string FBirthDate { get; set; }

    public virtual TVorder FOrder { get; set; }
}