// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class VHotelOrderDetailView
{
    public int FHotelOrderDetailId { get; set; }

    public string FHotelOrderId { get; set; }

    public string FRoomNumber { get; set; }
}