// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class VHotelOrderView
{
    public string 訂單編號 { get; set; }

    public string 顧客姓名 { get; set; }

    public string 飯店名稱 { get; set; }

    public string 房型名稱 { get; set; }

    public string 入住時間 { get; set; }

    public string 退房時間 { get; set; }

    public int? 入住人數 { get; set; }

    public decimal? 原始金額 { get; set; }

    public decimal? 目前金額 { get; set; }

    public string 優惠券名稱 { get; set; }

    public int? 數量 { get; set; }

    public decimal? 總金額 { get; set; }

    public string 付款方式 { get; set; }

    public string 付款狀態 { get; set; }

    public string 訂單日期 { get; set; }

    public string 付款日期 { get; set; }
}