// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class VHotelView
{
    public int FHotelId { get; set; }

    public string 飯店中文名稱 { get; set; }

    public string 飯店英文名稱 { get; set; }

    public string 地址 { get; set; }

    public string 電話 { get; set; }

    public string 地區 { get; set; }

    public string 統編 { get; set; }

    public int? 房型數量 { get; set; }
}