// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjTravelPlatformV3.Models;

public partial class VRoomTypeView
{
    public int FRoomTypeId { get; set; }

    public int? 床數 { get; set; }

    public string 床型 { get; set; }

    public int? 可容納人數 { get; set; }

    public decimal 手機 { get; set; }

    public string 房型名稱 { get; set; }

    public int? 房間數量 { get; set; }
}